from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
RESOURCES_DIR = BASE_DIR / "resources"
CACHE_DIR = RESOURCES_DIR / "cache"
PERSIST_DIR = RESOURCES_DIR / "persist"
LOGS_DIR = BASE_DIR / "logs"
MODELS_DIR = BASE_DIR / "models"
TRANSLATOR_LOGS_DIR = LOGS_DIR / "translators"
USAGE_STATS_FILE = CACHE_DIR / "usage_stats.json"
SUBTITLE_CACHE_FILE = CACHE_DIR / "subtitle_translation_cache.json"

NEW_LINE_SIGN = "\n"
HARD_NEW_LINE_SIGN = "\r\n"
BIG_NEW_LINE_SIGN = "\\N"
EQUAL_SIGN = "="
PLUS_SIGN = "+"
MINUS_SIGN = "-"
UNDERGROUND_SIGN = "_"
SLASH_SIGN = "/"
DOT_SIGN = "."
COMMA_SIGN = ","
SEMICOLON_SIGN = ";"
AMPERSAND_SIGN = "&"
ASTERISK_SIGN = "*"
QUESTION_SIGN = "?"
RIGHT_COMA_SIGN = ")"
LEFT_COMA_SIGN = "("
SPACE_SIGN = " "
FIRST_GROUP = "\\1"
SECOND_GROUP = "\\2"
EMPTY_STRING = ""
QUOTE_JOINER = ", "
SEMICOLON_JOINER = "; "

ZERO_SIGN = "0"
ZERO_INT_SIGN = 0

WEBVTT = "WEBVTT"
NOT_VTT_ERROR = "Это не субтитры WEBVTT."

DEFAULT_BATCH_SIZE = 21
DEFAULT_THREAD_COUNT = 3
DEFAULT_MAX_LEN = 7000
SMART_SPLIT_MAX_LINES = 4
SMART_SPLIT_MAX_WORDS = 40
SMART_SPLIT_MAX_CHARS = 220
SMART_SPLIT_MAX_GAP_MS = 800
SMART_SPLIT_MAX_DURATION_MS = 6000
SMART_SPLIT_COMMA_WINDOW = 3
__all__ = [
    "AMPERSAND_SIGN",
    "ASTERISK_SIGN",
    "BASE_DIR",
    "BIG_NEW_LINE_SIGN",
    "CACHE_DIR",
    "COMMA_SIGN",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_MAX_LEN",
    "DEFAULT_THREAD_COUNT",
    "DOT_SIGN",
    "EMPTY_STRING",
    "EQUAL_SIGN",
    "FIRST_GROUP",
    "HARD_NEW_LINE_SIGN",
    "LEFT_COMA_SIGN",
    "LOGS_DIR",
    "MINUS_SIGN",
    "MODELS_DIR",
    "NEW_LINE_SIGN",
    "NOT_VTT_ERROR",
    "PERSIST_DIR",
    "PLUS_SIGN",
    "QUESTION_SIGN",
    "QUOTE_JOINER",
    "RESOURCES_DIR",
    "RIGHT_COMA_SIGN",
    "SECOND_GROUP",
    "SEMICOLON_JOINER",
    "SEMICOLON_SIGN",
    "SLASH_SIGN",
    "SMART_SPLIT_COMMA_WINDOW",
    "SMART_SPLIT_MAX_CHARS",
    "SMART_SPLIT_MAX_DURATION_MS",
    "SMART_SPLIT_MAX_GAP_MS",
    "SMART_SPLIT_MAX_LINES",
    "SMART_SPLIT_MAX_WORDS",
    "SPACE_SIGN",
    "SUBTITLE_CACHE_FILE",
    "TRANSLATOR_LOGS_DIR",
    "UNDERGROUND_SIGN",
    "USAGE_STATS_FILE",
    "WEBVTT",
    "ZERO_INT_SIGN",
    "ZERO_SIGN",
]
